### ISSUE TITLE
ACC LAB TOOLS FROM THE LAC REGION TO SUPPORT UNDP SIGNATURE SOLUTIONS 

### ISSUE THREAD

**Issue by AnaGriEsp** [UNDP-Accelerator-Labs/toolkit-template#3]
### Purpose of the Toolkit

The toolkit is aiming to gather and organize the work of our region to share concrete tools that can be used and replicated by other country offices. As the Acc Lab Global Team puts it, 'to put the findings and learnings of the Acc Lab Network at the fingertips of all UNDP’. 

### Toolkit Name

ACC LAB TOOLS FROM THE LAC REGION TO SUPPORT UNDP SIGNATURE SOLUTIONS 

### Organization/Department Details

Acc Lab Network in the LAC region

**Comment by this-pama** [comment]
Thank you for submitting this. The toolkit has been setup and can be access [here](https://github.com/UNDP-Accelerator-Labs/RBLAC-SIGNATURE-SOLUTIONS). Cheers.
